#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ -z "${SSH_CONNECTION}" ]]; then
    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
fi

if [ -d $HOME/.bashrc.d ]; then
    for i in $HOME/.bashrc.d/* ; do
        if [ -f "$i" ]; then
            . "$i"
        fi
    done
fi

